In [4]:
import numpy as np
import cv2
import os

IMG_DIR = 'csv-maker/no-test/'

for img in os.listdir(IMG_DIR):
        img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)

        img_array = (img_array.flatten())

        img_array  = img_array.reshape(-1, 1).T

        print(img_array)

        with open('no-test.csv', 'ab') as f:

            np.savetxt(f, img_array, delimiter=",")

[[1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]]
[[16 16 16 ... 16 16 16]]
[[3 3 3 ... 1 2 2]]
[[0 0 0 ... 0 0 0]]
[[7 7 7 ... 5 5 5]]
[[10 10 10 ... 10 10 10]]
[[0 0 0 ... 0 0 0]]
[[252 254 255 ... 255 255 255]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[5 6 4 ... 8 7 7]]
[[167   0  23 ...  22  22  22]]
[[16 16 16 ... 49 49 74]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[16 16 16 ... 16 14 14]]
[[ 0  6  6 ... 10 10 10]]
[[0 0 0 ... 0 0 0]]
[[15 16 16 ... 15 15 15]]
[[10 10 10 ... 10 10 10]]
[[29 18 24 ... 24 24 24]]
[[6 6 6 ... 6 5 5]]
[[254 251 255 ...   2   2   2]]
[[9 9 9 ... 9 8 9]]
[[255 255 255 ... 255 255 255]]
[[9 9 9 ... 9 8 9]]
[[255   5  10 ...   8   8   8]]
[[ 0  3  7 ... 13 13 12]]
[[0 0 0 ... 1 1 0]]
[[11 11 11 ... 12 12 12]]
[[2 3 3 ... 2 2 3]]
